spring:
  config: 
    import: optional:file:.env[.properties]
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

server:
  port: 8081